#!/bin/bash

sudo rm -rf /usr/lib/mythicos/mythicstore
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
mkdir -p debian/mythicstore/usr/share/mythicos/mythicstore
cd resources && sudo glib-compile-resources \
    --target=/usr/share/mythicos/mythicstore/mythicstore.gresource mythicstore.gresource.xml \
    && cd ..

DEBUG=1 mythicstore
